version: "3.8"
services:
    db:
        image: postgres:15-alpine
        ports:
            - 5432:5432
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=mydb

    backend:
        env_file:
            - .env
        build:
            context: .
            dockerfile: DockerFile.prod
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - db
